# The UUID of the Task to edit
string uuid

# The human-readable name for the Task
string name

# The ROS Action that the Task executes
string action_server_name

# The version of the Task
string version

# The numerical data to pass to the action_server_name
float64[] floats

# The string data to pass to the action_server_name
string[] strings

# Boolean value which determines whether a mission using this task can continue
# if this task fails to execute
bool allow_failure
---
# The edited Task, or null if no Task with the given ID exists
clearpath_navigation_msgs/Task result
