# Watchdog status message containing information related to device 
# monitoring and what action has been taken to recover from an error


NodeStatusConfig[] node_status_config
NodeletStatusConfig[] nodelet_status_config
TopicDataConfig[] topic_data_config
HeartbeatConfig[] heartbeat_config
# GNSSDataConfig[] gnss_data_config
# CovarianceConfig[] covariance_config
# RTKDataConfig[] rtk_data_config
InclinationConfig[] inclination_config
# LiDARDataConfig[] lidar_data_config
# NumPointsConfig[] num_points_config
# PercentagePoints[] percentage_points_config
# CommunicationConfig[] communication_config
