# Watchdog config message containing information related to device
# monitoring and what action should be taken to recover from an error


WatchdogConfigCommunication[] communication_config
WatchdogConfigEmergencyStop[] emergency_stop_config
WatchdogConfigHeartbeat[] heartbeat_config
WatchdogConfigInclination[] inclination_config
WatchdogConfigNodeStatus[] node_status_config
WatchdogConfigNodeletStatus[] nodelet_status_config
WatchdogConfigNumPoints[] num_points_config
WatchdogConfigOdomCovariance[] odom_covariance_config
WatchdogConfigRtkFix[] rtk_fix_config
WatchdogConfigTopicData[] topic_data_config
