# Watchdog status message containing information related to device 
# monitoring and what action has been taken to recover from an error


WatchdogConfigNodeStatus[] node_status_config
WatchdogConfigNodeletStatus[] nodelet_status_config
WatchdogConfigCommunication[] communication_config
WatchdogConfigTopicData[] topic_data_config
WatchdogConfigHeartbeat[] heartbeat_config
# WatchdogConfigCovariance[] covariance_config
WatchdogConfigRtkFix[] rtk_fix_config
WatchdogConfigInclination[] inclination_config
WatchdogConfigNumPoints[] num_points_config
