# Action definition for executing a NetworkMission by uuid

# goal
string mission_uuid
string map_uuid

---
# result

uint8 UNKNOWN = 0
uint8 CANCELLED = 1
uint8 COLLISION = 2
uint8 PLANNING = 3
uint8 START_TASKS = 4
uint8 END_TASKS = 5
uint8 MISSION_TASKS = 6
uint8 code

bool success
string message
clearpath_navigation_msgs/NetworkGoalState[] goal_states

---
# feedback
string message
clearpath_navigation_msgs/NetworkGoalState[] goal_states
clearpath_navigation_msgs/NetworkMissionSegment network_plan