# Location of fans.

# Common Core (CC01)
uint8 CC01_FAN1=0
uint8 CC01_FAN2=1
uint8 CC01_FAN3=2
uint8 CC01_FAN4=3
uint8 CC01_FAN5=4
uint8 CC01_FAN6=5
uint8 CC01_FAN7=6
uint8 CC01_FAN8=7

# Ridgeback (R100)
uint8 R100_EQUIPMENT_BAY_INTAKE=0
uint8 R100_EQUIPMENT_BAY_EXHAUST=1
uint8 R100_CHARGER_BAY_INTAKE=2
uint8 R100_CHARGER_BAY_EXHAUST=3
uint8 R100_USER_BAY_INTAKE=4
uint8 R100_USER_BAY_EXHAUST=5

# Possible fan states
uint8 FAN_OFF=0
uint8 FAN_ON_HIGH=1
uint8 FAN_ON_LOW=2

# Control for the fans
uint8[] fans
