# Service definition to add a dock to the list of available docks

# A dock information message for the dock to be added
clearpath_dock_msgs/DockInfo dock
---
# True if the dock has been added successfully, otherwise False
bool success
string message