# The mission we're adding to the schedule
clearpath_mission_scheduler_msgs/ScheduledMission mission

# The UUID of the schedule
string schedule_id

# The zero-based index to insert the object into or removing from
# When removing by position, make sure to leave uuid empty
int32 position
---
# True if the mission was was added successfully, otherwise False
bool ok
