# Action definition for executing a schedule on-demand
# Potentially only useful for debugging

# The UUID of the schedule to execute
string uuid

# Wait this long before starting the schedule
duration delay
---
# Did the schedule terminate successfully?
bool success
---
# The mission we're executing right now
clearpath_mission_scheduler_msgs/ScheduledMission current_mission

# One of "waiting" or "executing" indicating what the schedule is doing
string state
