# Action definition for approaching the CLearpath UGV from the predock point to the dock point.

# goal
uint8 DOCK = 0
uint8 UNDOCK = 1

uint8 type
bool enable_predock
---
# result
bool success
---
# feedback
string state
float64 dist_to_dock # (IN DEVELOPMENT)
