# Action definition for sending a Clearpath UGV to one of its charging docks.

# goal
string uuid
bool local_mode
---
# result
bool success
---
# feedback
string state

# the distance of the charger_link to the dock target
float64 distance_to_dock
